### ISSUE TITLE
Docker Image v0.8.1 is broken

### ISSUE THREAD

**Issue by AndHain** [inovex/mqtt_blackbox_exporter#55]
Running the current Docker image version v0.8.1 fails with the following message

```
/bin/mqtt_blackbox_exporter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /bin/mqtt_blackbox_exporter)
/bin/mqtt_blackbox_exporter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /bin/mqtt_blackbox_exporter)
```

Docker command
```
docker run --rm -it -p 9214:9214 -v ${PWD}/:/data/ inovex/mqtt_blackbox_exporter:v0.8.1 -config.file /data/config.yaml
```

Config yaml
```yaml
probes:
  - name: broker
    broker_url: tcp://mybroker.mybroker:1883
    topic: test/mybroker
    client_prefix: prefix
    messages: 10
    interval: 30s
```

Could you please have a look?

**Comment by frittentheke** [comment]
On what OS and version are you running this?

**Comment by AndHain** [comment]
Local: macOS 13.5.2

In a k8s setup it doesn't work either.

**Comment by sowiszcze** [comment]
Can confirm the same happening in my environment.
```
$ docker --version
Docker version 24.0.7, build afdd53b
$ cat /proc/version
Linux version 6.1.0-16-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12)
```
Although I'm using docker compose instead.
<details>

<summary>Related parts of docker-compose.yml</summary>

```yml
version: '3.9'

services:
  blackbox-exporter:
    container_name: mqtt-blackbox-exporter
    image: inovex/mqtt_blackbox_exporter:${MQTT_BLACKBOX_EXPORTER_VERSION:-v0.8.1}
    command: -config.file /data/config.yaml
    networks:
      - default
      - monitoring
      - proxy
    volumes:
      - /srv/mqtt-blackbox-exporter:/data
    restart: unless-stopped

networks:
  default:
  monitoring:
    external: true
  proxy:
    external: true
```
</details>

<details>

<summary>If that helps, here's also my /srv/mqtt-blackbox-exporter/config.yaml</summary>

```yml
probes:
  - name: mqtt-broker
    broker_url: # REDACTED
    topic: internal/monitoring/mqtt-broker
    username: # REDACTED
    password: # REDACTED
    client_prefix: mqtt_blackbox_exporter.mqtt-broker
    messages: 10
    interval: 30s
```
</details>

Edit/fyi: Downgrading docker image to `v0.7.0` works around the issue.
